version: '3'
services:
  # app-alpine:
  #   build:
  #     context: .
  #     dockerfile: ./docker/alpine/Dockerfile
  #   tty: true
  #   environment:
  #     TZ: Asia/Tokyo
  #   volumes:
  #     - .:/root/project
  #   depends_on:
  #     - mariadb
  #     - postgres

  app-ubuntu:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/root/project
    depends_on:
      - mysql
      - mariadb
      - postgres

  mysql:
    image: mysql:8
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo

  mariadb:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo

  postgres:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: Asia/Tokyo

  adminer:
    image: adminer:4.8.1-standalone
    tty: true
    ports:
      - 9002:8080
    depends_on:
      - mysql
      - mariadb
      - postgres
