version: '3'
services:
  app-alpine:
    build:
      context: .
      dockerfile: ./docker/alpine/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/root/project
    depends_on:
      - mariadb
      - postgres

  app-ubuntu:
    build:
      context: .
      dockerfile: ./docker/ubuntu/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/root/project
    depends_on:
      - mysql
      - mariadb
      - postgres

  mysql:
    image: mysql:8
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allographer
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      TZ: Asia/Tokyo

  mariadb:
    image: mariadb
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allographer
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      TZ: Asia/Tokyo

  postgres:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: allographer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      TZ: Asia/Tokyo
